CREATE TABLE users(
id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
first_name VARCHAR(40) NOT NULL,
last_name VARCHAR(40) NOT NULL,
email VARCHAR(60) UNIQUE NOT NULL,
registration_date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
role VARCHAR(20) NOT NULL,
username VARCHAR(40) UNIQUE NOT NULL,
password VARCHAR(90) NOT NULL,
is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE application_servers(
id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
server_name VARCHAR(40) UNIQUE NOT NULL
); 

CREATE TABLE programming_languages(
id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
language_name VARCHAR(40) UNIQUE NOT NULL
); 

CREATE TABLE databases(
id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
database_name VARCHAR(40) UNIQUE NOT NULL
); 

CREATE TABLE projects(
id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
project_name VARCHAR(40) UNIQUE NOT NULL,
project_description VARCHAR(400) NOT NULL,
employee_count INT NOT NULL,
creation_date_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
user_id BIGINT REFERENCES users (id) ON DELETE SET null,
programming_language_id BIGINT REFERENCES programming_languages (id),
application_server_id BIGINT REFERENCES application_servers (id),
database_id BIGINT REFERENCES databases (id),
is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);


CREATE TABLE tasks(
id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
task_name VARCHAR(40) NOT NULL, 
task_description VARCHAR(400),
creation_date_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
user_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
project_id BIGINT REFERENCES projects (id) ON DELETE CASCADE,
is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);


CREATE INDEX users_index
ON users (username, registration_date_time);

CREATE INDEX projects_index
ON projects (project_name, creation_date_time, user_id);

CREATE INDEX tasks_index
ON tasks (project_id, task_name, creation_date_time, user_id);


insert into application_servers(server_name) 
values ('Apache Tomcat');
insert into application_servers(server_name) 
values ('Jetty');
insert into application_servers(server_name) 
values ('Apache TomEE');
insert into application_servers(server_name) 
values ('Oracle WebLogic');
insert into application_servers(server_name) 
values ('WebSphere');
insert into application_servers(server_name) 
values ('WildFly');
insert into application_servers(server_name) 
values ('GlassFish');


insert into programming_languages (language_name) 
values ('C');
insert into programming_languages (language_name) 
values ('C++');
insert into programming_languages (language_name) 
values ('Java');
insert into programming_languages (language_name) 
values ('Go');
insert into programming_languages (language_name) 
values ('Haskel');
insert into programming_languages (language_name) 
values ('Kotlin');
insert into programming_languages (language_name) 
values ('Swift');
insert into programming_languages (language_name) 
values ('JavaScript');
insert into programming_languages (language_name) 
values ('Python');
insert into programming_languages (language_name) 
values ('Ruby');


insert into databases  (database_name) 
values ('MySQL');
insert into databases  (database_name) 
values ('Microsoft SQL Server');
insert into databases  (database_name) 
values ('PostgreSQL');
insert into databases  (database_name) 
values ('Redis');
insert into databases  (database_name) 
values ('MongoDB');
insert into databases  (database_name) 
values ('Apache Cassandra');
/* /////////////////////////////////////////////////////////////
 */
/*'testuser1', 'pass1'
'testuser2', 'pass2'
*/
insert into users (first_name, last_name, email, role, username, password) 
values ('Fred', 'Barret', 'hellofred@gmail.com', 'ROLE_USER', 'testuser1', '$2a$10$uJ7XLt9W3PsirlZsTQLMkuhSM1vQqzPDAi6q10Dz88WuP7mFDGB2u');
insert into users (first_name, last_name, email, role, username, password) 
values ('Kate', 'Rassel', 'hellokate@mail.ru', 'ROLE_USER', 'testuser2', '$2a$10$dCvvkLjmHvGKZ3PoME.Ydu94u.i2fOHAoqmiZI05qckjXMLugnZKS');

/*'testadmin1', 'pass1'
'testadmin2', 'pass2'
*/
insert into users (first_name, last_name, email, role, username, password) 
values ('Andry', 'Mitchel', 'helloandry@gmail.com', 'ROLE_ADMIN', 'testadmin1', '$2a$10$KGBtGJmwS6gtj0zw89k4OuZ0e8l0sOZrAM/Tl4L7spkdkKnwORWrK');
insert into users (first_name, last_name, email, role, username, password) 
values ('Joshua', 'Klein', 'hellojoshua@gmail.com', 'ROLE_ADMIN', 'testadmin2', '$2a$10$b9GwLf3dAW8oUvG.OCZJ6.qQb/n/khNlbuAPDYSIjUJrCx2nHymjC');

insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id, is_deleted) 
values ('Amazing data project', 'The best project of the explored part of the universe using Java', 25, 1, 3, 2, 3, true);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('Test project', 'MVC b2b platform', 13, 2, 2, 1, 4);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id, is_deleted) 
values ('Test project1', 'MVC b2b platform1', 7, 4, 3, 2, 1, true);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('Test project2', 'MVC b2b platform2', 118, 3, 1, 1, 1);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('Rest test', 'REST b2b platform', 28, 1, 5, 6, 6);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('test rest1', 'wow REST b2b platform', 13, 2, 4, 5, 5);

insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('11Amazing data project', '66The best project of the explored part of the universe using Java', 14, 2, 4, 1, 5);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('22Test project', '55MVC b2b platform', 16, 4, 4, 4, 4);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('33Test project1', '44MVC b2b platform1', 56, 2, 4, 3, 6);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('44Test project2', '33MVC b2b platform2', 44, 3, 2, 5, 5);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('55Rest test', '22REST b2b platform', 24, 1, 3, 2, 4);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('66test rest1', '11wow REST b2b platform', 255, 3, 3, 3, 6);

insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('bbAmazing data project', 'yyThe best project of the explored part of the universe using Java', 16, 3, 2, 1, 3);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('ccTest project', 'ttMVC b2b platform', 14, 3, 2, 1, 2);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('aaTest project1', 'hhMVC b2b platform1', 15, 3, 3, 3, 4);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('ddTest project2', 'bbMVC b2b platform2', 34, 2, 4, 3, 1);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('ffRest test', 'nnREST b2b platform', 15, 2, 5, 6, 2);
insert into projects(project_name, project_description, employee_count, user_id, programming_language_id, application_server_id, database_id) 
values ('eetest rest1', 'kkwow REST b2b platform', 144, 1, 1, 5, 5);

insert into tasks(task_name, task_description, user_id, project_id) 
values ('some task1', 'this is task description1', 1, 4);

insert into tasks(task_name, task_description, user_id, project_id) 
values ('some task2', 'this is task description2', 2, 4);

insert into tasks(task_name, task_description, user_id, project_id) 
values ('some task3', 'this is task description3', 2, 4);

insert into tasks(task_name, task_description, user_id, project_id) 
values ('some task4', 'this is task description4', 3, 4);

insert into tasks(task_name, task_description, user_id, project_id) 
values ('some task5', 'this is task description5', 3, 4);

insert into tasks(task_name, task_description, user_id, project_id) 
values ('some task6', 'this is task description6', 4, 4);